### ISSUE TITLE
Potential fix: update controlsfx dependency to prevent illegal-access-error

### ISSUE THREAD

**Issue by miho** [fair-acc/chart-fx#537]
Thanks for creating this awesome library!

Using the library in modern Java results in an illegal-access-error, even if the JavaFX-Plugin for Maven/Gradle is used which handles all the `--add-module` arguments.

In https://github.com/fair-acc/chart-fx/issues/409 it is assumed that the **"correct"** module-args would solve the issue. That doesn't seem to be correct though (except if we are willing to essentially bypass encapsulation, which is definitely not the right way to fix it).

There's a simple fix though: update the controlsfx dependency: `11.0.0 -> 11.1.1`. Some minor changes have to be done due to changes in the `BreadCrumbButton`. The most recent controlsfx version doesn't seem to rely on opening private API anymore.

I will create PR with the necessary changes.

Here's the exception I am seeing:

```
Caused by: java.lang.IllegalAccessError: superclass access check failed: class impl.org.controlsfx.behavior.RangeSliderBehavior (in unnamed module @0x712a2ca4) cannot access class com.sun.javafx.scene.control.behavior.BehaviorBase (in module javafx.controls) because module javafx.controls does not export com.sun.javafx.scene.control.behavior to unnamed module @0x712a2ca4
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
```

**Comment by wirew0rm** [comment]
Should be fixed by #538, @miho please feel free to reopen if the issue persists.

Thank you for the report and the fix.
One thing probably left to do is to remove the module options in the readme and the pom. I'll try to remember to do that.
